name: {{ name.snakeCase() }}_workspace
publish_to: none
environment:
  sdk: '>=3.12.0 <4.0.0'
workspace:
  - apps/{{ name.snakeCase() }}
  - features/counter/feature_counter
dev_dependencies:
  melos: ^8.6.0
melos:
  name: {{ name.snakeCase() }}
  command:
    version:
      workspaceChangelog: false
