include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - packages/vyuh_cli/bricks/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - directives_ordering
    - prefer_const_constructors

