name: vyuh
repository: https://github.com/vyuh-tech/vyuh

packages:
  - packages/{sanity,system,}/*
  - packages/{sanity,system,}/*/example
  - examples/*
  - examples/*/*
  - apps/*

command:
  version:
    workspaceChangelog: false
    fetchTags: false
    updateGitTagRefs: false
    includeCommitId: false
    linkToCommits: false
    hooks:
      post: melos run update_version

ide:
  intellij:
    moduleNamePrefix: ''

scripts:
  update_version:
    run: dart run tools/update_version.dart
