# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All the packages are specified by their name and not path.
        # This is because the package is passed to the 'melos exec' command
        package:
          - vyuh_cache
          - vyuh_core
          - vyuh_extension_content
          - vyuh_cli
          - vyuh_test
          - vyuh_widgetbook
          - vyuh_plugin_content_provider_sanity
          - vyuh_plugin_storage_hive
          - vyuh_plugin_storage_secure
          - vyuh_plugin_storage_shared_preferences
          - vyuh_content_widget
          - vyuh_plugin_telemetry_provider_console
          - vyuh_feature_developer
          - vyuh_feature_system
          - vyuh_feature_onboarding
          - vyuh_feature_auth
          - sanity_client
          - flutter_sanity_portable_text
        include:
          - package: vyuh_plugin_storage_secure
            path: packages/plugins
            test: true
          - package: vyuh_feature_system
            path: packages/system
            test: true
          - package: vyuh_cache
            path: packages/system
            test: true
          - package: vyuh_plugin_content_provider_sanity
            path: packages/sanity
            test: true
          - package: vyuh_core
            path: packages/system
            test: true
          - package: sanity_client
            path: packages/sanity
            test: true
          - package: flutter_sanity_portable_text
            path: packages/sanity
            test: true

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.2'
          channel: stable
      - name: Install dependencies
        run: |
          dart pub get --enforce-lockfile

      - name: Analyze package
        run: dart --packages=.dart_tool/package_config.json tools/melos.dart exec --scope="${{ matrix.package }}" -- dart analyze --fatal-infos

      - name: Run tests
        if: matrix.test
        run: dart --packages=.dart_tool/package_config.json tools/melos.dart exec --scope="${{ matrix.package }}" -- flutter test --coverage

      - name: Upload coverage reports to Codecov
        if: matrix.test
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          files: ${{ matrix.path }}/${{ matrix.package }}/coverage/lcov.info
          slug: vyuh-tech/vyuh
